[package]
name = "image_permute"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.23"
imageproc="0.22"
rayon="1.5"
glob="0.3"
rand="0.8"
conv = "0.3"
num = "0.4"